resources:
  
  # Monitoring
  - ../vendor/katalog/monitoring/prometheus-operator
  - ../vendor/katalog/monitoring/prometheus-operated
  - ../vendor/katalog/monitoring/grafana
  - ../vendor/katalog/monitoring/configs
  - ../vendor/katalog/monitoring/goldpinger
  - ../vendor/katalog/monitoring/kube-proxy-metrics
  - ../vendor/katalog/monitoring/kube-state-metrics
  - ../vendor/katalog/monitoring/node-exporter

  # Logging
  - ../vendor/katalog/logging/elasticsearch-single
  - ../vendor/katalog/logging/cerebro
  - ../vendor/katalog/logging/curator
  - ../vendor/katalog/logging/fluentd
  - ../vendor/katalog/logging/kibana

  # Ingress
  - ../vendor/katalog/ingress/nginx
  - ../vendor/katalog/ingress/forecastle
  - ../vendor/katalog/ingress/cert-manager

  # Ingress definitions
  - resources/ingress.yml

patchesStrategicMerge:

  - patches/prometheus-operated-resources.yml
  - patches/prometheus-operator-resources.yml
  - patches/grafana-resources.yml
  - patches/kibana-resources.yml
  - patches/elasticsearch-resources.yml
  - patches/fluentd-resources.yml
  - patches/fluentbit-resources.yml
  - patches/nginx-ingress-controller-resources.yml
